### ISSUE TITLE
composer require address

### ISSUE THREAD

**Issue by johnjogrady** [dr-matt-smith/pdo-crud-for-free-repositories#1]
Hi Matt,

The install command is slightly different on Packagist

I think it should be 
composer require mattsmithdev/pdo-crud-for-free

not 
composer require mattsmithdev/pdo-crud-for-free-repositories (this returns not found)
THanks

john

**Comment by dr-matt-smith** [comment]
thanks for comment:

these are 2 different projects - one using a separate Repository class, and one without
I've moved in favour of the Repository approach

I should probably 
(a)
make the old project as abandonded

(b) 
update this Repo project and do a proper release

- when I get time I'll do these things  :-)

.. matt ..
