### ISSUE TITLE
possible change of method name needed in Usage step 3

### ISSUE THREAD

**Issue by johnjogrady** [dr-matt-smith/pdo-crud-for-free-repositories#2]
// create the new Dvd row
    $dvdRepository = new DvdRepository();
    $id = $dvdRepository->insert($dvd);

Hi Matt, I think the insert() method noted above should be create() as DatabaseTableRepository class has only a create() method and not an insert() method

**Comment by dr-matt-smith** [comment]
quite right
- I can never quite make up my mind between 'insert' and 'create'
(one from SQL and one from CRUD)

but, as you say, since method is 'create()' I'll update docs to reflect ths

thanks

.. matt ..
